services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP API
      - "9000:9000"  # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: idftask
      CLICKHOUSE_USER: idftask
      CLICKHOUSE_PASSWORD: idftask
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 10s
      retries: 5


# version: '3.8'
# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: airflow
#       POSTGRES_PASSWORD: airflow
#       POSTGRES_DB: airflow
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "airflow"]
#       interval: 5s
#       retries: 5
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   clickhouse:
#     image: yandex/clickhouse-server:latest
#     ports:
#       - "8123:8123"  # HTTP API
#       - "9000:9000"  # Native protocol
#     volumes:
#       - clickhouse_data:/var/lib/clickhouse
#     environment:
#       CLICKHOUSE_DB: airflow
#       CLICKHOUSE_USER: airflow
#       CLICKHOUSE_PASSWORD: airflow
#     healthcheck:
#       test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
#       interval: 5s
#       timeout: 10s
#       retries: 5

#   airflow-webserver:
#     image: apache/airflow:2.7.2
#     environment:
#       AIRFLOW__CORE__EXECUTOR: LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
#       AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#       AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
#     volumes:
#       - ./dags:/opt/airflow/dags
#       - ./logs:/opt/airflow/logs
#       - ./plugins:/opt/airflow/plugins
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#       - clickhouse
#     healthcheck:
#       test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
#       interval: 10s
#       timeout: 10s
#       retries: 5

#   airflow-scheduler:
#     image: apache/airflow:2.7.2
#     environment:
#       AIRFLOW__CORE__EXECUTOR: LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
#       AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#     volumes:
#       - ./dags:/opt/airflow/dags
#       - ./logs:/opt/airflow/logs
#       - ./plugins:/opt/airflow/plugins
#     depends_on:
#       - postgres
#       - clickhouse

volumes:
  # postgres_data:
  clickhouse_data: