
version: 2

sources:
  - name: idftask  # Должно совпадать с именем схемы в БД
    tables:
      - name: people
      
models:
  - name: people_in_space_aggregated
    columns:
      - name: craft
        tests:
          - not_null
      - name: astronaut_count
        tests:
          - not_null

